//
//  TTAppDelegate+DataProvider.m
//  DonetskWeather
//
//  Created by Boyko A.V. on 10.07.13.
//  Copyright (c) 2013 IDS Test Task. All rights reserved.
//

#import "TTAppDelegate+DataProvider.h"
#import "TTWeatherItem.h"
#import "NSDate+Day.h"

NSString *const kTTNotificationDataUpdated = @"TTNotificationDataUpdated";

@implementation TTAppDelegate (DataProvider)
@dynamic donetsk;
@dynamic managedObjectModel,managedObjectContext,persistentStoreCoordinator;

-(void) preloadData{
    TTCity *donetsk = self.donetsk;
    if (donetsk==nil) {
        donetsk = [NSEntityDescription
                               insertNewObjectForEntityForName:@"City"
                               inManagedObjectContext:self.managedObjectContext];
        
        donetsk.name = @"Donetsk";
        donetsk.idx = @"919163";
        [self saveContext];
    }
}
//
// DESCRIPTION: Add weather items to city
// PARAMS:      NSArray with TTWeatherItems
// RESULT:      void
//
-(void) addWeatherItem:(NSArray*)items city:(TTCity*)city{
    NSManagedObjectContext *context = self.managedObjectContext;
    if (!context)
        return;
    for (TTWeatherItem *item in items) {
              
        TTWeather *weather = [self weatherForDay:item.date city:city];
        BOOL createNew = NO;
        if (weather==nil) {
            weather = [NSEntityDescription insertNewObjectForEntityForName:@"Weather"
                                                        inManagedObjectContext:context];
            weather.date = item.date;
            createNew = YES;
        }

        weather.text = item.text;
        if (item.temp!=TTWEATHER_TEMP_NONE) {
            weather.temp = @(item.temp);
        }
        weather.tempHigh = @(item.tempHigh);
        weather.tempLow = @(item.tempLow);
        weather.code = @(item.code);
        if (createNew) {
            [city addWheterObject:weather];
        }
    }
    [self saveContext];

}

//
// DESCRIPTION: Add weather items to Donetsk city
// PARAMS:
// RESULT:      void
//
-(void) addWeatherItem:(NSArray*)items{
    [self addWeatherItem:items city:self.donetsk];
}


//
// DESCRIPTION: get weathers for two days
// PARAMS:      city
// RESULT:      array of TTWeather
//
-(TTWeather*) weatherForDay:(NSDate*)date city:(TTCity*)city{
    NSManagedObjectContext *context = self.managedObjectContext;
    if (!context)
        return nil;
    
    TTWeather *weather = nil;
    
    NSDate *startDate  = [date begginOfDay];
    NSDate *endDate = [date endOfDay];
    
    NSFetchRequest *fetchRequest = [[NSFetchRequest alloc] init];
    fetchRequest.entity = [NSEntityDescription
                           entityForName:@"Weather" inManagedObjectContext:context];;
    fetchRequest.predicate = [NSPredicate predicateWithFormat:@"((SELF IN %@) AND (date >= %@) AND (date <= %@))",city.wheter,startDate,endDate];
    
    NSError *error = nil;
    weather = [[context executeFetchRequest:fetchRequest error:&error] lastObject];
    return weather;
}

//
// DESCRIPTION: get weathers for two days (donetsk)
// PARAMS:
// RESULT:      array of TTWeather
//
-(TTWeather*) weatherForDay:(NSDate*)date{
    return [self weatherForDay:date city:self.donetsk];
}

-(TTCity*) donetsk{
    TTCity *result = nil;
    NSManagedObjectContext *context = self.managedObjectContext;
    if (context) {
        NSFetchRequest *fetchRequest = [[NSFetchRequest alloc] init];
        NSEntityDescription *entity = [NSEntityDescription
                                       entityForName:@"City" inManagedObjectContext:context];
        [fetchRequest setEntity:entity];
        NSError *error = nil;
        NSArray *fetchedObjects = [context executeFetchRequest:fetchRequest error:&error];
        if (fetchedObjects.count>0) {
            result = fetchedObjects[0];
        }
    }
    return result;

}

//
// MARK: - Autogenerated
//
- (void)saveContext{
    NSError *error = nil;
    NSManagedObjectContext *managedObjectContext = self.managedObjectContext;
    if (managedObjectContext != nil) {
        if ([managedObjectContext hasChanges]) {
            if ([managedObjectContext save:&error]) {
                [[NSNotificationCenter defaultCenter] postNotificationName:kTTNotificationDataUpdated object:nil];
            }else{
                // Replace this implementation with code to handle the error appropriately.
                // abort() causes the application to generate a crash log and terminate. You should not use this function in a shipping application, although it may be useful during development.
                NSLog(@"Unresolved error %@, %@", error, [error userInfo]);
                abort();
            }
        }
    }
}


#pragma mark - Core Data stack

// Returns the managed object context for the application.
// If the context doesn't already exist, it is created and bound to the persistent store coordinator for the application.
- (NSManagedObjectContext *)managedObjectContext
{
    if (_managedObjectContext != nil) {
        return _managedObjectContext;
    }
    
    NSPersistentStoreCoordinator *coordinator = [self persistentStoreCoordinator];
    if (coordinator != nil) {
        _managedObjectContext = [[NSManagedObjectContext alloc] init];
        [_managedObjectContext setPersistentStoreCoordinator:coordinator];
    }
    return _managedObjectContext;
}

// Returns the managed object model for the application.
// If the model doesn't already exist, it is created from the application's model.
- (NSManagedObjectModel *)managedObjectModel
{
    if (_managedObjectModel != nil) {
        return _managedObjectModel;
    }
    NSURL *modelURL = [[NSBundle mainBundle] URLForResource:@"Model" withExtension:@"momd"];
    _managedObjectModel = [[NSManagedObjectModel alloc] initWithContentsOfURL:modelURL];
    return _managedObjectModel;
}

// Returns the persistent store coordinator for the application.
// If the coordinator doesn't already exist, it is created and the application's store added to it.
- (NSPersistentStoreCoordinator *)persistentStoreCoordinator
{
    if (_persistentStoreCoordinator != nil) {
        return _persistentStoreCoordinator;
    }
    
    NSURL *storeURL = [[self applicationDocumentsDirectory] URLByAppendingPathComponent:@"data.sqlite"];
    
    NSError *error = nil;
    _persistentStoreCoordinator = [[NSPersistentStoreCoordinator alloc] initWithManagedObjectModel:[self managedObjectModel]];
    if (![_persistentStoreCoordinator addPersistentStoreWithType:NSSQLiteStoreType configuration:nil URL:storeURL options:nil error:&error]) {
        /*
         Replace this implementation with code to handle the error appropriately.
         
         abort() causes the application to generate a crash log and terminate. You should not use this function in a shipping application, although it may be useful during development.
         
         Typical reasons for an error here include:
         * The persistent store is not accessible;
         * The schema for the persistent store is incompatible with current managed object model.
         Check the error message to determine what the actual problem was.
         
         
         If the persistent store is not accessible, there is typically something wrong with the file path. Often, a file URL is pointing into the application's resources directory instead of a writeable directory.
         
         If you encounter schema incompatibility errors during development, you can reduce their frequency by:
         * Simply deleting the existing store:
         [[NSFileManager defaultManager] removeItemAtURL:storeURL error:nil]
         
         * Performing automatic lightweight migration by passing the following dictionary as the options parameter:
         @{NSMigratePersistentStoresAutomaticallyOption:@YES, NSInferMappingModelAutomaticallyOption:@YES}
         
         Lightweight migration will only work for a limited set of schema changes; consult "Core Data Model Versioning and Data Migration Programming Guide" for details.
         
         */
        NSLog(@"Unresolved error %@, %@", error, [error userInfo]);
        abort();
    }
    
    return _persistentStoreCoordinator;
}

#pragma mark - Application's Documents directory

// Returns the URL to the application's Documents directory.
- (NSURL *)applicationDocumentsDirectory
{
    return [[[NSFileManager defaultManager] URLsForDirectory:NSDocumentDirectory inDomains:NSUserDomainMask] lastObject];
}

@end
